remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
#theme: minima
title: Moving the Goll Posts
description: Random stuff I want to elaborate on
author: Aviv Goll
show_downloads: false
github:
  is_project_page: false
  is_user_page: true
