remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
#theme: minima
title: Title in Progress..
description: Random stuff I want to elaborate on
show_downloads: false
github:
  is_project_page: false
  is_user_page: true
